spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticketing
    username: ticketing
    password: ticketing
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  #logging:
  #  level:
  #    org.hibernate.SQL: debug
  #    org.hibernate.orm.jdbc.bind: trace


oauth:
  kakao:
    client-id: 7a889156fb592faaa652c408b78be729
    token-uri: https://kauth.kakao.com/oauth/token
    api-uri: https://kapi.kakao.com/v2/user/me
    redirect-uri: http://localhost:8080/api/v1/auth/kakao/callback

jwt:
  secret-key: aawodijwaiodjawodijawiojwodjawiojdioawjdoiajdiowas
  access-token-expiration-seconds: 1800
  onboarding-token-expiration-seconds: 900